const NAME_SPACE = 'calendar';

export const GET_WEATHER_REQUEST = `${NAME_SPACE}/GET_WEATHER_REQUEST`;
export const GET_WEATHER_SUCCESS = `${NAME_SPACE}/GET_WEATHER_SUCCESS`;
export const GET_WEATHER_ERROR = `${NAME_SPACE}/GET_WEATHER_ERROR`;

export default {
  GET_WEATHER_REQUEST,
  GET_WEATHER_SUCCESS,
  GET_WEATHER_ERROR,
};
