const NAME_SPACE = 'calendar';

export const ADD_REMINDER = `${NAME_SPACE}/ADD_REMINDER`;
export const REMOVE_REMINDER = `${NAME_SPACE}/REMOVE_REMINDER`;
export const EDIT_REMINDER = `${NAME_SPACE}/EDIT_REMINDER`;

export const GET_WEATHER_REQUEST = `${NAME_SPACE}/GET_WEATHER_REQUEST`;
export const GET_WEATHER_SUCCESS = `${NAME_SPACE}/GET_WEATHER_SUCCESS`;
export const GET_WEATHER_ERROR = `${NAME_SPACE}/GET_WEATHER_ERROR`;

export default {
  ADD_REMINDER,
  REMOVE_REMINDER,
  EDIT_REMINDER,
  GET_WEATHER_REQUEST,
  GET_WEATHER_SUCCESS,
  GET_WEATHER_ERROR,
};
